
python_download_url: https://centos7.iuscommunity.org/ius-release.rpm
python_downloads_path: /usr/bin 

python_yum_packages_3:
  - python36u
  - python36u-devel
  - python36u-pip
  - python36u-libs
  - groupinstall

python_pip_packages: []
python_update_pip: no
python_update_setuptools: no
python_install_virtualenv: no
python_pip_executable: 
# python_pip_version:           # default to latest
# python_setuptools_version:    # default to latest
# python_virtualenv_version:    # default to latest
