apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "jupyterhub.fullname" . }}
    app.kubernetes.io/deploy-manager: ksonnet
  name: {{ .Values.service.name }}-0
spec:
  clusterIP: None
  ports:
  - name: hub
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{ template "jupyterhub.fullname" . }}
  sessionAffinity: None
  type: ClusterIP
  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "jupyterhub.fullname" . }}-lb
    app.kubernetes.io/deploy-manager: ksonnet
  name: {{ .Values.service.name }}-lb
spec:
  ports:
  - name: hub
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{ template "jupyterhub.fullname" . }}
  sessionAffinity: None
  type: ClusterIP

