- lineinfile: dest={{ eclipse_home }}/eclipse.ini line='-Xverify:none'
- lineinfile: dest={{ eclipse_home }}/eclipse.ini line='-clean' insertbefore='-startup'
- replace: dest={{ eclipse_home }}/eclipse.ini regexp='(--launcher\.XXMaxPermSize)\n256m' replace='\1\n512m'

- name: Add the Eclipse to the system path (/etc/profile)
  lineinfile:
    dest: /etc/profile
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
    state: present
  with_items:
    - regexp: "^ECLIPSE_HOME=/opt/eclipse/"
      line: "ECLIPSE_HOME=/opt/eclipse/"
    - regexp: "^PATH=.*ECLIPSE_HOME.*"
      line: "PATH=$PATH:$ECLIPSE_HOME/bin"

- name: source variables
  become: yes
  shell: source /etc/profile

