- include: install_{{ ansible_distribution }}.yml
- debug: var=eclipse_home
- debug: var=eclipse
- file: src={{ eclipse }} dest=/usr/local/bin/eclipse state=link remote_src=true
- include: cleanups.yml
#- include: features.yml
- include: lombok.yml
- include: config.yml
