kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "postgre.fullname" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
