apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgre.fullname" . }}
  labels:
    app: {{ template "postgre.name" . }}
    chart: {{ template "postgre.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  postgres-username: {{ .Values.postgredbUsername | b64enc | quote }}
  postgres-database: {{ .Values.postgredbDatabase | b64enc | quote }}
  {{- if .Values.usePassword }}
  {{- if .Values.postgresRootPassword }}
  postgres-root-password:  {{ .Values.postgresPassword | b64enc | quote }}
  {{- else }}
  postgres-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if and .Values.postgredbUsername .Values.postgredbDatabase }}
  {{- if .Values.postgredbPassword }}
  postgres-password:  {{ .Values.mongodbPassword | b64enc | quote }}
  {{- else }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
